[package]
name = "devops"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dunce = "1"
env_logger = "0.11"
log = "0.4"
walkdir = "2"
