name: Upload CodeCov
description: Upload code coverage report to CodeCov
runs:
  using: composite
  steps:
    - run: |
        devops rust-code-coverage
        rm --force --recursive ./target-coverage/report/html
      shell: bash
    - uses: codecov/codecov-action@v4
