name: Install DevOps
description: Install DevOps
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ~/.rustup
          ./target-install
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml', '.github/**/*.yaml') }}
        restore-keys: ${{ runner.os }}-rust-
    - run: |
        rustup component add llvm-tools-preview
        cargo install --git https://github.com/seamlik/devops.git --force
        cargo install grcov --force
      shell: bash
      env:
        CARGO_TARGET_DIR: ./target-install
