on:
  - push
  - pull_request
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-devops
      - uses: ./.github/actions/cache-nodejs
      - run: npm install --global prettier

      # Verify
      - run: prettier --write **/*.yaml **/*.md
      - run: cargo fmt
      - uses: ./.github/actions/check-formatting
      - run: cargo test
